### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by styler00dollar** [Zedd1558/Image-Inpainter#1]
Thank you so much for creating this. For some reason it is quite hard to find proper python inpainting GUIs. I did a quick test with deepfill and it saves a lot of time with deep learning research. I tested it on Linux since deep learning mainly done there and made some observations, not sure how much my observations apply to Windows. A few points I would like to mention:
- I noticed that it is possible to use arrow keys to move inside the picture when zoom is used, but some (optional?) bars at the right and below for movement with mouse would be nice. It is a bit hard to do movement when only the mouse is used, since movement with zoom is not that easy. I noticed that shift can be used to do vertical movement, but it zooms, once the border is reached.
- If you click the button to open a picture in the main window, the "Open file image..." dialog is behind the main inpainter,py window. It is needed to move the main window, before the button is clicked, so the file explorer is visible. Same goes for saving an image. The window is behind the inpainting interface and not visible. It is needed to make the window small, so the file explorer save window is visible in the middle of the screen. Since windows have some kind of forced behaviour to be at the front, these windows can't be made visible by seleting them and will stay invisible with normal usage.
- For some reason, it is needed to click the yellow "fullscreen" button twice, before the picture is properly placed. If only done once, the picture is weirdly placed and does not fill the entire screen.
![example](https://user-images.githubusercontent.com/51405565/93214322-4fc09480-f765-11ea-8c82-77ff48636c27.jpg)
![example2](https://user-images.githubusercontent.com/51405565/93216279-d37b8080-f767-11ea-971d-2ba591844f4d.jpg)
- A bit documentation on how to add custom inpainting methods would be appreciated. I just replaced ```Telea``` for testing purposes.

**Comment by zahid58** [comment]
Thank you so much for you valuable and insightful suggestions. I will work on these GUI issues as soon as I can. I will make sure it works correctly on linux and add necessary documentations.

**Comment by zahid58** [comment]
- added scrollbar that pops up when needed right and below, movement while zooming is easier now.
- the *open image* and *save image* windows now opens on top of the frame.
- the image in properly placed on the viewer when maximized
- you can now go back to normal mode from maximized mode when same button is pressed again
- added instructions on the *Readme* on "how to add other inpainting methods" with very few lines of codes.

Thank you for pointing out the issues. Please feel free to open up another issue if the problems persist or any other problem arises.
